# Generated by Django 3.1.2 on 2020-10-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_db',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_img', models.ImageField(upload_to='')),
                ('Product_name', models.CharField(max_length=50)),
                ('Product_desc', models.TextField()),
                ('Product_price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
    ]
